<?php

namespace ContainerGW4pE3G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RateController' shared autowired service.
     *
     * @return \App\Controller\RateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RateController.php';

        $container->services['App\\Controller\\RateController'] = $instance = new \App\Controller\RateController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\RateController', $container));

        return $instance;
    }
}
