<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGW4pE3G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGW4pE3G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGW4pE3G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGW4pE3G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGW4pE3G\App_KernelDevDebugContainer([
    'container.build_hash' => 'GW4pE3G',
    'container.build_id' => 'f84304f5',
    'container.build_time' => 1703002677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGW4pE3G');
